version: "3.3"

services:
  app:
    build: .
    command: bash start.sh
    restart: on-failure
    ports:
      - "2365:2365"
      - "5620:5620"

networks:
  default:
    external: true
    name: network18
